[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"  # Fixed to version that does not use PUSH0
evm_version = "london"   # Use london EVM for compatibility

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
